spring:
  datasource:
    url: jdbc:h2:mem:oneul_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
cloud:
  aws:
    bucket: ${AWS_BUCKET}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
